# Generated by Django 6.1.1 on 2026-10-06 20:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_barres', models.CharField(max_length=40, unique=True)),
                ('etat_physique', models.CharField(choices=[('bon', 'Bon état'), ('abime', 'Abîmé')], default='bon', max_length=10)),
                ('statut', models.CharField(choices=[('disponible', 'En rayon'), ('emprunte', 'Emprunté'), ('reserve', 'Mis de côté'), ('perdu', 'Perdu'), ('retire', 'Retiré du fonds')], default='disponible', max_length=12)),
                ('etagere', models.CharField(blank=True, max_length=40)),
                ('code_rayon', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=120)),
                ('categorie', models.CharField(blank=True, max_length=80)),
                ('annee_publication', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('langue', models.CharField(default='Français', max_length=30)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_vente', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('adherent', 'Adhérent'), ('bibliothecaire', 'Bibliothécaire'), ('administrateur', 'Administrateur')], default='adherent', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('actif', 'Actif'), ('suspendu', 'Suspendu')], default='actif', max_length=12)),
                ('numero_carte', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('suspendu_jusqu', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('canal', models.CharField(choices=[('comptoir', 'Au comptoir'), ('en_ligne', 'En ligne')], default='comptoir', max_length=10)),
                ('mode_paiement', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('mobile', 'Mobile money'), ('carte', 'Carte')], max_length=10)),
                ('adresse_livraison', models.CharField(blank=True, max_length=250)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de préparation'), ('prete', 'Prête'), ('en_livraison', 'En livraison'), ('terminee', 'Terminé'), ('annulee', 'Annulé')], default='en_attente', max_length=14)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_achat'],
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(default=django.utils.timezone.localdate)),
                ('date_retour_prevue', models.DateField(blank=True, null=True)),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('prete', 'Prêt à retirer'), ('en_cours', 'En cours'), ('retard', 'En retard'), ('rendu', 'Rendu'), ('perdu', 'Perdu'), ('annule', 'Annulé')], default='en_cours', max_length=10)),
                ('adresse_livraison', models.CharField(blank=True, max_length=250)),
                ('nb_prolongations', models.PositiveSmallIntegerField(default=0)),
                ('motif_sanction', models.CharField(blank=True, max_length=200)),
                ('montant_sanction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut_paiement', models.CharField(blank=True, choices=[('impayee', 'Impayée'), ('payee', 'Payée'), ('annulee', 'Annulée')], max_length=10)),
                ('date_sanction', models.DateTimeField(blank=True, null=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprunts_acceptes', to=settings.AUTH_USER_MODEL)),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to='bibliotheque.exemplaire')),
            ],
            options={
                'ordering': ['-date_emprunt', '-id'],
            },
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplaires', to='bibliotheque.livre'),
        ),
        migrations.CreateModel(
            name='LigneAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_applique', models.DecimalField(decimal_places=2, max_digits=10)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='bibliotheque.achat')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliotheque.livre')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('achat', 'livre'), name='une_ligne_par_livre_et_achat')],
            },
        ),
    ]
