"""
Django settings for biblio_site project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%2e8hnkli^*8=y%yv&pb*p+4d(w^($=ydpm7q76i9(x#zmt+b%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'bibliotheque',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'biblio_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bibliotheque.context.globales',
            ],
        },
    },
]

WSGI_APPLICATION = 'biblio_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "fr"
TIME_ZONE = "Africa/Douala"
AUTH_USER_MODEL = "bibliotheque.Utilisateur"
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "apres_connexion"
LOGOUT_REDIRECT_URL = "accueil"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# ---------- Règles de la bibliothèque (à modifier ici) ----------
BIBLIO = {
    "duree_pret_jours": 14,              # durée d'un prêt
    "max_emprunts": 3,                   # emprunts simultanés par adhérent (demandes en ligne comprises)
    "max_prolongations": 1,              # prolongations par prêt
    "duree_prolongation_jours": 7,
    "amende_par_jour": 100,              # FCFA par jour de retard
    "amende_plafond": 5000,              # FCFA, 0 = pas de plafond
    "frais_perte": 500,                  # FCFA, s'ajoutent au prix du livre perdu
    "coef_suspension": 1,                # jours de suspension par jour de retard (0 = aucune)
    "delai_retrait_jours": 3,            # une demande/commande prête non retirée est annulée après ce délai
    "max_commandes_invite_actives": 3,   # nombre maximal de commandes en attente par e-mail/téléphone
    "max_quantite_achat_en_ligne": 5,    # quantité maximale d’un même livre par commande en ligne
    "duree_adhesion_jours": 365,
    "validation_adhesion_requise": True, # True : les inscrits en ligne sont validés au comptoir
    "horaires": "Lundi – vendredi : 8h – 17h, samedi : 9h – 13h",
    "adresse": "",
}
